auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
frontend:
  max_outstanding_per_tenant: 2048
pattern_ingester:
  enabled: true
limits_config:
  max_global_streams_per_user: 0
  # Default 500
  max_query_series: 10000
  ingestion_rate_mb: 50000
  ingestion_burst_size_mb: 50000
  volume_enabled: true
query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

storage_config:
  # Index files will be written locally at /loki/index and, eventually,
  # will be shipped to the storage via tsdb-shipper
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    # cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
  aws:
    # s3: http://minioadmin:minioadmin@minio.:9000/loki
    bucketnames: loki-data
    endpoint: minio:9000
    access_key_id: loki
    secret_access_key: supersecret
    insecure: true
    # http_config:
    #   idle_conn_timeout: 90s
    #   response_header_timeout: 0s
    #   insecure_skip_verify: false
    s3forcepathstyle: true

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      # object_store: filesystem
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
#
# Statistics help us better understand how Loki is used, and they show us performance
# levels for most users. This helps us prioritize features and documentation.
# For more information on what's sent, look at
# https://github.com/grafana/loki/blob/main/pkg/analytics/stats.go
# Refer to the buildReport method to see what goes into a report.
#
# If you would like to disable reporting, uncomment the following lines:
analytics:
  reporting_enabled: false
